#!/bin/sh
set -eu

cd "$(dirname "$0")"

for FILE in $(ls tests/algo/*.cpp); do
	set -f
	clang-tidy-10 ${FILE} --header-filter=.* --extra-arg="--std=c++2a"
	set +f
done
for FILE in $(ls tests/thin/*.cpp); do
	set -f
	clang-tidy-10 ${FILE} --header-filter=.* --extra-arg="--std=c++2a"
	set +f
done
