name: CMake+CTest - Build and test

on:
  push:
    paths:
      - include/*
      - tests/*
      - CMakeLists.txt
      - .github/workflows/build_and_test.yml
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build and test
        run: ctest --build-and-test . build --parallel --build-generator "Unix Makefiles" --test-command ctest --output-on-failure
